typo and SyntaxError, correction?
Modification to repair this error:
Extracting robotframework_pdf2textlibrary-0.3-py3.8.egg to c:\python3\lib\site-packages
  File "c:\python3\lib\site-packages\robotframework_pdf2textlibrary-0.3-py3.8.egg\Pdf2TextLibrary\__init__.py", line 11
    print 'pdt to text library'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('pdt to text library')?